
[default_gamerule]
	hasFallAnimation = true
	#Range: 0 ~ 100
	weightPenalty = 25
	disapleEntityUI = false
	keepSkills = true
	doVanillaAttack = true
	globalStun = true
	stiffComboAttacks = true
	canSwitchCombat = true

[loot]
	#Range: -100 ~ 100
	skill_book_mob_drop_chance_modifier = -100
	#Range: -100 ~ 100
	skill_book_chest_drop_chance_modifier = -100

